export const mukellefList = [
    {
        id: "1",
        adi:"",
        soyadi:"",
        unvani:"AKKURT GIDA BESİCİLİK",
        yetkili:"Cihangir İNEL",
        tc:"12323123123",
        kurulusTarihi:"01.01.1998",
        kapanısTarihi:"",
        faaliyetKodu:"463104",
        faaliyetAdi:"Diğer",
        vergiDairesiKodu:"055251",
        vergiDairesi:"19 MAYIS VERGİ DAİRESİ",
        vergiililce:"SAMSUN",
        vergiKimlikNo:"0300081636",
        ticSicilNo:"27115",
        tescilTarihi:"01.01.1998",
        tescilYeri:"SAMSUN",
        kdvMukellefi:"Var",
        kdvVergiDairesiKodu:"",
        kdvVergiDairesi:"",
        kdvVergiDairesiililce:"",
        mersisNo:"0030008163600018",
        taahhütEdilensermaye:"0.00",
        odenmisSermaye:"0.00",
        bagliSosyalGuvKur:"",
        sosGuvKurNo:"",
        bagliMesTes:"",
        mesTesNo:"",
        basitUsulFaaliyetKodu:"",
        basitOnayAdi:"",
        basitOnaySoyadi:"",
        basitOnayTc:"",
    },
    {
        id: "2",
        adi:"",
        soyadi:"",
        unvani:"CODEAD YAZILIM",
        yetkili:"Faruk KESKİNSOY",
        tc:"32215121204",
        kurulusTarihi:"01.07.2017",
        kapanısTarihi:"",
        faaliyetKodu:"463104",
        faaliyetAdi:"Diğer",
        vergiDairesiKodu:"055251",
        vergiDairesi:"ÇEKİRGE VERGİ DAİRESİ",
        vergiililce:"BURSA",
        vergiKimlikNo:"0707087636",
        ticSicilNo:"27116",
        tescilTarihi:"01.01.1998",
        tescilYeri:"BURSA",
        kdvMukellefi:"Var",
        kdvVergiDairesiKodu:"",
        kdvVergiDairesi:"",
        kdvVergiDairesiişilce:"",
        mersisNo:"0030008163600020",
        taahhütEdilensermaye:"0.00",
        odenmisSermaye:"0.00",
        bagliSosyalGuvKur:"",
        sosGuvKurNo:"",
        bagliMesTes:"",
        mesTesNo:"",
        basitUsulFaaliyetKodu:"",
        basitOnayAdi:"",
        basitOnaySoyadi:"",
        basitOnayTc:"",
    },
];
export const mukellefExtraInfo = [
    {
        id: 1,
        isim:"Cihangir",
        soyisim:"İNEL",
        tc:"12323123123",
        phone:"5308886667",
        email:"c.inel@gmail.com"
    },
    {
        id: 2,
        isim:"Faruk",
        soyisim:"KESKİNSOY",
        tc:"32215121204",
        phone:"5308652121",
        email:"f.keskinsoy@gmail.com"
    },
];


export const iller=['Adana', 'Adıyaman', 'Afyon', 'Ağrı', 'Amasya', 'Ankara', 'Antalya', 'Artvin',
'Aydın', 'Balıkesir', 'Bilecik', 'Bingöl', 'Bitlis', 'Bolu', 'Burdur', 'Bursa', 'Çanakkale',
'Çankırı', 'Çorum', 'Denizli', 'Diyarbakır', 'Edirne', 'Elazığ', 'Erzincan', 'Erzurum', 'Eskişehir',
'Gaziantep', 'Giresun', 'Gümüşhane', 'Hakkari', 'Hatay', 'Isparta', 'Mersin', 'İstanbul', 'İzmir', 
'Kars', 'Kastamonu', 'Kayseri', 'Kırklareli', 'Kırşehir', 'Kocaeli', 'Konya', 'Kütahya', 'Malatya', 
'Manisa', 'Kahramanmaraş', 'Mardin', 'Muğla', 'Muş', 'Nevşehir', 'Niğde', 'Ordu', 'Rize', 'Sakarya',
'Samsun', 'Siirt', 'Sinop', 'Sivas', 'Tekirdağ', 'Tokat', 'Trabzon', 'Tunceli', 'Şanlıurfa', 'Uşak',
'Van', 'Yozgat', 'Zonguldak', 'Aksaray', 'Bayburt', 'Karaman', 'Kırıkkale', 'Batman', 'Şırnak',
'Bartın', 'Ardahan', 'Iğdır', 'Yalova', 'Karabük', 'Kilis', 'Osmaniye', 'Düzce']